version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      ./.env
    volumes:
      - .docker/volumes/postgres_data:/var/lib/postgresql/data
